export const REDUX = {
    //GOOGLE AUTH REDUCER
    GOOGLE_LOGGED_IN: 'GOOGLE_LOGGED_IN',
    GOOGLE_FIREBASE_KEY: 'GOOGLE_FIREBASE_KEY',
    GOOGLE_UPDATE_INFO: 'GOOGLE_UPDATE_INFO',
    GOOGLE_UPDATE_TOKEN: 'GOOGLE_UPDATE_USER_TOKEN',
    // Facebook auth reducer
    FACEBOOK_LOGGED_IN: 'FACEBOOK_LOGGED_IN',
    FACEBOOK_FIREBASE_KEY: 'FACEBOOK_FIREBASE_KEY',
    FACEBOOK_UPDATE_INFO: 'FACEBOOK_UPDATE_INFO',
    FACEBOOK_UPDATE_USER_TOKEN: 'FACEBOOK_UPDATE_USER_TOKEN',
    // Auth reducer
    LOGGED_IN : 'LOGGED_IN',
    UPDATE_USER_INFO:'UPDATE_USER_INFO',
    ADD_USER_INFO : 'ADD_USER_INFO',
    DELETE_USER_INFO : 'DELETE_USER_INFO'
  };
  