export const REDUX = {
  //CLEAR DATA
  CLEAR_DATA: 'CLEAR_DATA',

  //GOOGLE AUTH REDUCER
  GOOGLE_LOGGED_IN: 'GOOGLE_LOGGED_IN',
  GOOGLE_FIREBASE_KEY: 'GOOGLE_FIREBASE_KEY',
  GOOGLE_UPDATE_INFO: 'GOOGLE_UPDATE_INFO',
  GOOGLE_UPDATE_TOKEN: 'GOOGLE_UPDATE_USER_TOKEN',
  // Facebook auth reducer
  FACEBOOK_LOGGED_IN: 'FACEBOOK_LOGGED_IN',
  FACEBOOK_FIREBASE_KEY: 'FACEBOOK_FIREBASE_KEY',
  FACEBOOK_UPDATE_INFO: 'FACEBOOK_UPDATE_INFO',
  FACEBOOK_UPDATE_USER_TOKEN: 'FACEBOOK_UPDATE_USER_TOKEN',
  // Auth reducer
  LOGGED_IN: 'LOGGED_IN',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  ADD_USER_INFO: 'ADD_USER_INFO',
  DELETE_USER_INFO: 'DELETE_USER_INFO',
  // Keyword Search 
  ADD_KEYWORD: 'ADD_KEYWORD',
  UPDATE_KEYWORD: 'UPDATE_KEYWORD',
  UPDATE_KEYWORD_LIST: 'UPDATE_KEYWORD_LIST',
  CLEAR_ALL_KEYWORD: 'CLEAR_ALL_KEYWORD',
  REMOVE_KEYWORD: 'REMOVE_KEYWORD',
  SEARCH_WITH_KEYWORD: 'SEARCH_WITH_KEYWORD',
  // noti
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
  SET_ALL_NOTIFICATION: 'SET_ALL_NOTIFICATION',
  DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  ADD_MOVIE_NOTIFICATION: 'ADD_MOVIE_NOTIFICATION'
};
